dist: xenial
language: node_js

cache:
  directories:
    - /home/travis/.mongodb/versions
jobs:
  include:
    - stage: replicaset
      node_js: 4
      env:
        - MONGODB_VERSION=4.0.x
        - MONGODB_ENVIRONMENT=replicaset
    - stage: sharded
      node_js: 4
      env:
        - MONGODB_VERSION=4.0.x
        - MONGODB_ENVIRONMENT=sharded

  allow_failures:
    - env:
        - MONGODB_VERSION=4.0.x
        - MONGODB_ENVIRONMENT=sharded
